# C4: C1 + BGP on (BIRD 상주 비용 분리).
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    nodeAddressAutodetectionV4:
      interface: eth1
    bgp: Enabled
    ipPools:
      - name: default-ipv4-ippool
        blockSize: 26
        cidr: 172.16.0.0/16
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
---
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}
